version: '3.4'

services:
  apiministeriorecomeco:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=R00TR00T
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DB_ENDPOINT=localhost
      - DB_MIGRATE=true
      - DB_INITIALIZE=true    
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/https:ro