version: '3.4'
services:
  apiministeriorecomeco:
    image: ${DOCKER_REGISTRY-}apiministeriorecomeco
    container_name: apiministeriorecomeco
    build:
      context: .
      dockerfile: /Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: mysql:8.0.27
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: ministeriodb
      MYSQL_PASSWORD: R00TR00T
      MYSQL_ROOT_PASSWORD: R00TR00T
volumes:
  db-volume: