version: '3.4'
services:
  apiministeriorecomeco:
    image: ${DOCKER_REGISTRY-}apiministeriorecomeco
    container_name: apiministeriorecomecoapp
    build:
      context: .
      dockerfile: /Dockerfile
    depends_on:
      - database
    ports: 
      - "5000:80"
      - "5001:443" 
 
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apiministeriorecomecodb
    ports:
      - 1433:1433 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "R00TR00T"