version: '3.4'
services:
  ApiMinisterioRecomeco:
    image: ${DOCKER_REGISTRY-}ministeriorecomecoapi
    build:
      context: .
      dockerfile: /Dockerfile
    depends_on:
      - sqlserver
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Teste"
      - "MSSQL_PID=Express"
    volumes:
      - c:\dados\volumes\sqlserver:/var/opt/mssql/data
    ports:
      - '1450:1433' 
