version: '3.4'
services:
  apiministeriorecomeco:
    image: ${DOCKER_REGISTRY-}apiministeriorecomeco
    container_name: apiministeriorecomecoapp
    build:
      context: .
      dockerfile: /Dockerfile
    depends_on:
      - sqldata
    ports: 
      - "5000:80"
      - "5001:443" 
 
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apiministeriorecomecodb
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=R00TR00T"
    ports:
      - 1450:1433  
