version: '3.4'

services:
  ApiMinisterioRecomeco:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=R00TR00T
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx  
    ports: 
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro