// <auto-generated />
using System;
using ApiMinisterioRecomeco.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMinisterioRecomeco.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230312090700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Celula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inclusao");

                    b.Property<string>("EmailLider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email_lider");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_endereco");

                    b.Property<string>("Horario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("horario");

                    b.Property<string>("NomeCelula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_celula");

                    b.Property<string>("NomeCoordenadores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_coordenadores");

                    b.Property<string>("NomeLider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_lider");

                    b.Property<string>("Rede")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rede");

                    b.Property<string>("Reuniao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reuniao");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone_contato");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Celulas");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("complemento");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inclusao");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rua");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Relatorio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inclusao");

                    b.Property<string>("NomeVida")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_vida");

                    b.Property<string>("NomeVoluntario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_voluntario");

                    b.Property<string>("RetornoContato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("retorno_contato");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Vida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Campus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campus");

                    b.Property<string>("Culto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("culto");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inclusao");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_endereco");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_civil");

                    b.Property<string>("HorarioCulto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("horario_culto");

                    b.Property<string>("NomeCelula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_celula");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeVoluntario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_voluntario");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao");

                    b.Property<string>("PossuiCelula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("possui_celula");

                    b.Property<string>("RedeSocial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rede_social");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone_contato");

                    b.Property<string>("TelefoneOutroContato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone_outro_contato");

                    b.Property<string>("TipoConversao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_conversao");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Vidas");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Voluntario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inclusao");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("LiderCelula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lider_celula");

                    b.Property<string>("LiderTreinamento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lider_treinamento");

                    b.Property<string>("NomeCelula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_celula");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeLider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_lider");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone_contato");

                    b.HasKey("Id");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Celula", b =>
                {
                    b.HasOne("ApiMinisterioRecomeco.Models.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("ApiMinisterioRecomeco.Models.Celula", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("ApiMinisterioRecomeco.Models.Vida", b =>
                {
                    b.HasOne("ApiMinisterioRecomeco.Models.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("ApiMinisterioRecomeco.Models.Vida", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
